plugins {
    id 'com.android.application'
    id 'com.google.gms.google-services'
}

android {
    namespace 'com.arewascope.app'
    compileSdk 35

    defaultConfig {
        applicationId 'com.arewascope.app'
        minSdk 23
        targetSdk 35
        versionCode 60
        versionName '1.6.0-notifications'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation platform('com.google.firebase:firebase-bom:33.7.0')
    implementation 'com.google.firebase:firebase-messaging'
}
